### ISSUE TITLE
probably an issue

### ISSUE THREAD

**Issue by Andrewrd364** [jcardama/csgo-market-sniper#13]
I noticed that sometimes the bot can't switch some pages in the browser, but the program is processing these next pages. Previously i had an issue that the bot bought wrong item. Is it the case when the bot found item, for example on 57th page but pressed the buy button on 36th page?
![image](https://github.com/jcardama/csgo-market-sniper/assets/133220836/0fae6503-012e-4c19-b9e3-37ea638c3e28)

And if you have pending balance in steam, the bot is parsing it wrong. In the screenshot i have 427,72 in actual balance.
Also if i want to check only the first page, the bot is switching pages.
![image](https://github.com/jcardama/csgo-market-sniper/assets/133220836/7c12ed0d-c423-4528-b6dc-74c4cef16f19)

**Comment by jcardama** [comment]
I've found that if you can't switch between pages it is because Steam is returning you an error, how it works is that when switching to a different page it queries from their servers the list of skins, in most cases if you can't switch is because the server returned an error, from my experience using the bot it is because I get rate limited, the only solution is just to wait until you are not rate limited anymore. 

And this shouldn't affect the correct pattern buying, with the latest version it should buy the correct item.
